### ISSUE TITLE
Where is the "model.h5" in "testing.py"?

### ISSUE THREAD

**Issue by diligentBilly** [Zauler/DQN_Temperature#1]
#CONSTRUCTION OF THE ENVIRONMENT BY CREATING AN OBJECT OF THE ENVIRONMENT CLASS
env = environment.Environment(optimal_temperature = (18.0, 24.0), initial_month = 0, initial_number_users=20, initial_rate_data = 30)
#LOADING OF A PRE-TRAINED MODEL
model = load_model("model.h5")
# CHOICE OF TRAINING MODE
train = False

Line 4:model = load_model("model.h5")
Where is the pre-trained model? Can you share it in the code? Thank you!

**Comment by diligentBilly** [comment]
I really hope I can run the caode in my computer for study! Thank you!

**Comment by Zauler** [comment]
Sorry, I didn't add any, however I have just updated so you can download the model already trained and working. I tested it before uploading it
